/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CamelCards: typeof import('./src/components/Day-7/CamelCards.vue')['default']
    Card: typeof import('./src/components/commons/Card.vue')['default']
    CubeConundrum: typeof import('./src/components/Day-2/CubeConundrum.vue')['default']
    Fertilizer: typeof import('./src/components/Day-5/Fertilizer.vue')['default']
    GearRatios: typeof import('./src/components/Day-3/GearRatios.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InputFile: typeof import('./src/components/commons/InputFile.vue')['default']
    Scratchcards: typeof import('./src/components/Day-4/Scratchcards.vue')['default']
    Trebuchet: typeof import('./src/components/Day-1/Trebuchet.vue')['default']
  }
}
